### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by drobison** [kriskowal/q-require#2]
When trying to install with npm I receive the following:

> npm WARN deprecated es5-shim@0.0.1: Please update to the latest version; it overrides noncompliant native methods even in modern implementations
> npm ERR! code ETARGET
> npm ERR! notarget No compatible version found: util@0.0.0
> npm ERR! notarget Valid install targets:
> npm ERR! notarget 0.4.9, 0.10.0, 0.10.1, 0.10.2, 0.10.3
> npm ERR! notarget
> npm ERR! notarget This is most likely not a problem with npm itself.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of 'q-fs'
> npm ERR! notarget

**Comment by kriskowal** [comment]
This package is ancient and marked "out of service".

The most recent incarnation is https://github.com/gutentags/system, which still uses Q internally, but might as well use standard promises today, so it may soon.

There are *many* alternatives, some of which are standards track.
